-- Demo content for development (applied only with the dev and test profiles via classpath:db/demo).
-- Everything here is fictional placeholder content: the team, testimonials, prices, address and phone number
-- are invented, and the before/after images are demonstration crops, not patient results.
-- Photography is Unsplash placeholder imagery referenced by URL; replace it from the admin dashboard.

-- Builds a consistent Unsplash URL. pg_temp functions disappear with the migration session.
CREATE FUNCTION pg_temp.u(photo TEXT, w INT DEFAULT 1600, h INT DEFAULT NULL, faces BOOLEAN DEFAULT FALSE) RETURNS TEXT
    LANGUAGE sql IMMUTABLE AS
$$
SELECT 'https://images.unsplash.com/photo-' || photo || '?auto=format&fit=crop&w=' || w
           || CASE WHEN h IS NULL THEN '' ELSE '&h=' || h END
           || CASE WHEN faces THEN '&crop=faces' ELSE '' END
           || '&q=80'
$$;

-- Development account. NEVER use it in production (the prod profile does not load this file).
--   admin@eloria.local / Admin123!   (ADMIN)
INSERT INTO users (name, email, password, role) VALUES
    ('Éloria Administrator', 'admin@eloria.local', '$2a$12$hwddRDq9ffHV6gXt9ut0RuxJL5CdRXOhnSbt9hRaDlQho92bilHoa', 'ADMIN');

UPDATE center_settings SET
    tagline       = 'Aesthetic medicine & skin care, Paris 8e',
    address_line  = '9 Rue Élise-Morel',
    postal_code   = '75008',
    city          = 'Paris',
    country       = 'France',
    phone         = '+33 1 99 00 24 80',
    email         = 'contact@eloria.example',
    opening_hours = E'Monday – Friday|9:00 – 20:00\nSaturday|10:00 – 18:00\nSunday|Closed',
    instagram_url = 'https://www.instagram.com/',
    facebook_url  = 'https://www.facebook.com/',
    pinterest_url = 'https://www.pinterest.com/',
    map_url       = 'https://www.openstreetmap.org/#map=16/48.8698/2.3075'
WHERE id = 1;

INSERT INTO treatment_categories (name, slug, description, display_order, active) VALUES
    ('Facial', 'facial', 'Considered facials that cleanse, hydrate and restore radiance, adapted to your skin on the day.', 1, TRUE),
    ('Advanced Skin', 'advanced-skin', 'Clinical resurfacing and renewal treatments, prescribed after a skin assessment.', 2, TRUE),
    ('Laser & Light', 'laser-light', 'Medical-grade laser and light technologies, always performed by trained practitioners.', 3, TRUE),
    ('Body', 'body', 'Non-invasive body treatments for contour, texture and firmness, paired with realistic goals.', 4, TRUE),
    ('Anti-Aging', 'anti-aging', 'Progressive protocols that support firmness and skin quality over time.', 5, TRUE),
    ('Skin Programs', 'skin-programs', 'Multi-session programs built around one concern and followed by the same specialist.', 6, TRUE);

INSERT INTO treatments (category_id, name, slug, short_description, description, duration_minutes, sessions, downtime,
                        price, price_from, benefits, preparation, aftercare, contraindications, technology,
                        main_image_url, main_image_alt, available, featured, created_at, updated_at)
SELECT c.id, v.name, v.slug, v.short_description, v.description, v.duration, v.sessions, v.downtime, v.price, v.price_from,
       v.benefits, v.preparation, v.aftercare, v.contraindications, v.technology, pg_temp.u(v.photo), v.alt,
       v.available, v.featured, now() - (v.age || ' days')::interval, now() - (v.age || ' days')::interval
FROM (VALUES
    ('facial', 'Signature Hydrafacial', 'signature-hydrafacial',
     'A three-step facial that cleanses, gently exfoliates and infuses hydrating serums, with no downtime.',
     'Our most requested facial. Using vortex technology, the treatment cleanses and gently exfoliates, extracts congestion without squeezing, then infuses serums chosen for your skin that day. Most clients leave with skin that looks fresher and feels comfortable, and can return to their day straight away.',
     60, 'Single session or monthly maintenance', 'None', 190.00, FALSE,
     E'Skin that looks clearer and more luminous\nGentle extraction of congestion\nHydration tailored to your skin on the day\nSuitable for most skin types',
     E'Avoid retinoids and exfoliating acids for 48 hours before\nArrive without heavy make-up if you can\nTell us about any recent treatments or new medication',
     E'Wear a broad-spectrum SPF 30 or higher\nAvoid saunas and intense exercise for 24 hours\nSkip exfoliating products for 48 hours',
     E'Active cold sores or skin infection in the area\nRecent facial surgery or laser treatment\nKnown allergy to any serum ingredient',
     'Hydrafacial vortex system', '1616394584738-fc6e612e71b9', 'Client relaxing during a hydrating facial', TRUE, TRUE, 120),
    ('facial', 'Facial Rejuvenation', 'facial-rejuvenation',
     'A sculpting facial combining manual lifting techniques with active serums for a rested, refined look.',
     'A slow, precise facial built around manual lifting and drainage techniques. Your practitioner works the facial muscles and connective tissue, then layers peptide and antioxidant serums. It is a treatment for skin that looks tired rather than a corrective procedure, and its effect is best maintained with regular sessions.',
     75, 'Every 3 to 4 weeks', 'None', 160.00, FALSE,
     E'A more rested, refreshed appearance\nSupports circulation and lymphatic flow\nRelaxes tension held in the jaw and forehead',
     E'Avoid sun exposure and self-tan for 48 hours before\nRemove contact lenses if you wear them',
     E'Drink water through the day\nAvoid heavy make-up for the rest of the day\nApply SPF every morning',
     E'Active skin infection or open lesions\nRecent injectable treatment (within 2 weeks)',
     'Manual facial sculpting, peptide serums', '1512290923902-8a9f81dc236c', 'Practitioner performing a manual facial', TRUE, FALSE, 118),
    ('facial', 'Deep Skin Cleansing', 'deep-skin-cleansing',
     'A thorough cleansing facial with steam, careful extraction and a calming mask for congested skin.',
     'Designed for skin prone to congestion and enlarged-looking pores. After a double cleanse and enzyme exfoliation, your therapist softens the skin with warm steam, performs careful extractions and finishes with a clay or calming mask depending on how your skin reacts.',
     60, 'Every 4 to 6 weeks', 'Possible mild redness for a few hours', 120.00, FALSE,
     E'Visibly clearer pores\nA smoother skin surface\nA calmer, more balanced complexion',
     E'Do not squeeze blemishes in the days before\nAvoid waxing or threading the face for 48 hours',
     E'Avoid make-up for 12 hours if possible\nKeep hands away from the face\nUse a gentle cleanser for 2 days',
     E'Active acne with painful inflamed lesions (a medical consultation is advised)\nRosacea flare-ups\nSunburn',
     'Enzyme exfoliation, steam, clay masks', '1570172619644-dfd03ed5d881', 'Mask being applied with a brush during a facial', TRUE, FALSE, 116),
    ('facial', 'Skin Hydration Ritual', 'skin-hydration-ritual',
     'An intensive moisture treatment for dehydrated, tight or sensitised skin, layered with hyaluronic serums.',
     'A comforting treatment for skin that feels tight or looks dull. Layers of hyaluronic acid, ceramides and a cooling hydrogel mask are applied in sequence while your therapist performs a soothing facial massage. Ideal before an event or after travel.',
     50, 'Single session or monthly', 'None', 140.00, FALSE,
     E'Skin that feels comfortable and supple\nA dewy, healthy-looking finish\nSoothes the feeling of tightness',
     E'No specific preparation needed\nLet us know if your skin is currently reactive',
     E'Keep using a gentle moisturiser morning and evening\nApply SPF daily',
     E'Known allergy to any product ingredient',
     'Hyaluronic acid and ceramide layering, hydrogel mask', '1599305090598-fe179d501227', 'Jar of hydrating cream on warm stone', TRUE, FALSE, 114),
    ('advanced-skin', 'Chemical Peels', 'chemical-peels',
     'Medical-grade peels, from gentle to deeper strengths, selected after a skin assessment.',
     'A chemical peel uses carefully selected acids to remove damaged surface cells and encourage renewal. We choose the formulation and strength after assessing your skin type, concerns and history. Lighter peels have little downtime; stronger peels may cause visible flaking for several days. Results build progressively and vary between individuals.',
     45, 'Course of 3 to 6, 2 to 4 weeks apart', '0 to 7 days depending on strength', 150.00, TRUE,
     E'Helps refine skin texture\nCan soften the look of pigmentation and fine lines\nSupports a more even tone over a course',
     E'A consultation is required before your first peel\nStop retinoids 5 to 7 days before\nAvoid sun exposure for 2 weeks before',
     E'Do not pick or peel flaking skin\nUse the post-peel kit as instructed\nStrict sun protection for 4 weeks',
     E'Pregnancy or breastfeeding\nIsotretinoin use in the past 6 months\nActive cold sores, eczema or broken skin in the area\nRecent tanning',
     'Glycolic, lactic, salicylic and TCA formulations', '1576426863848-c21f53c60b19', 'Dropper bottle of serum on white marble', TRUE, TRUE, 110),
    ('advanced-skin', 'Microneedling', 'microneedling',
     'Collagen induction therapy that creates controlled micro-channels to support skin renewal.',
     'Microneedling uses a sterile, single-use cartridge of fine needles to create controlled micro-channels in the skin. This prompts the skin’s own repair response, which can improve the look of texture, scarring and enlarged pores over a course of treatments. A topical anaesthetic keeps the treatment comfortable.',
     75, 'Course of 3 to 6, 4 to 6 weeks apart', '1 to 3 days of redness', 280.00, FALSE,
     E'Can soften the appearance of acne scarring\nHelps refine texture and pore appearance\nSupports firmer-looking skin over time',
     E'Consultation required before the first session\nStop retinoids and acids 5 days before\nAvoid blood-thinning supplements if your doctor agrees',
     E'No make-up for 24 hours\nAvoid sun, sauna and swimming for 72 hours\nUse only the recommended products for one week',
     E'Pregnancy\nActive acne, infection or cold sores\nKeloid scarring tendency\nBlood clotting disorders',
     'Medical microneedling device, single-use sterile cartridges', '1552693673-1bf958298935', 'Gloved practitioner treating a client’s skin', TRUE, TRUE, 108),
    ('advanced-skin', 'LED Light Therapy', 'led-light-therapy',
     'A painless light treatment using red and near-infrared wavelengths to calm and support the skin.',
     'Medical LED panels deliver specific wavelengths of light to the skin. Red and near-infrared light are used to support skin recovery and comfort, while blue light is used for blemish-prone skin. It is often added after peels or microneedling, or booked as a course on its own.',
     30, 'Course of 6 to 10, twice weekly', 'None', 80.00, FALSE,
     E'Comfortable and non-invasive\nSupports recovery after other treatments\nHelps calm visible redness',
     E'Arrive with clean skin\nTell us about any photosensitising medication',
     E'No special aftercare\nContinue your usual routine with SPF',
     E'Photosensitising medication\nEpilepsy triggered by light\nPregnancy (as a precaution)',
     'Medical-grade LED panels (415, 633 and 830 nm)', '1620916297397-a4a5402a3c6c', 'Hand holding a dropper of serum', TRUE, FALSE, 106),
    ('advanced-skin', 'Dermaplaning', 'dermaplaning',
     'Gentle manual exfoliation that removes dead surface cells and fine vellus hair for a smooth finish.',
     'Using a sterile surgical blade held at a careful angle, your therapist removes the outer layer of dead cells and fine facial hair. The result is skin that feels smooth and lets make-up and skincare sit more evenly. It is often combined with a hydrating mask.',
     40, 'Every 4 weeks', 'None', 110.00, FALSE,
     E'Immediately smoother-feeling skin\nRemoves fine vellus hair\nHelps skincare absorb evenly',
     E'Avoid retinoids for 3 days before\nNo waxing in the area for a week before',
     E'SPF every day\nAvoid exfoliating products for 3 days',
     E'Active acne or inflamed skin\nRecent sunburn\nCold sores',
     'Sterile single-use surgical blade', '1620916566398-39f1143ab7be', 'Tube of skincare resting on soft linen', TRUE, FALSE, 104),
    ('laser-light', 'Laser Hair Removal', 'laser-hair-removal',
     'Long-term hair reduction with a medical diode laser, adapted to your skin and hair type.',
     'Our diode laser targets the pigment in the hair follicle to reduce regrowth over a course of sessions. Settings are adapted to your skin tone and hair type after a patch test. Most people need several sessions because hair grows in cycles; results vary and occasional maintenance may be needed.',
     30, 'Course of 6 to 8, 4 to 8 weeks apart', 'Mild redness for a few hours', 90.00, TRUE,
     E'Long-term reduction of unwanted hair\nSuitable for most body areas\nFewer ingrown hairs for many clients',
     E'Patch test at least 48 hours before the first session\nShave the area the day before\nNo waxing, plucking or tanning for 4 weeks before',
     E'Avoid sun exposure on the area for 2 weeks\nNo hot baths or sauna for 24 hours\nApply a soothing gel if needed',
     E'Pregnancy\nTanned skin or recent self-tan\nPhotosensitising medication\nActive skin infection in the area',
     'Medical diode laser 810 nm with contact cooling', '1540555700478-4be289fbecef', 'Clean white bottle and folded towel', TRUE, FALSE, 102),
    ('laser-light', 'Laser Skin Resurfacing', 'laser-skin-resurfacing',
     'Fractional laser resurfacing for texture, fine lines and scarring, performed by our medical team.',
     'Fractional laser treats a fraction of the skin in microscopic columns, leaving surrounding tissue intact to speed recovery. It is used to improve the appearance of texture, fine lines and some scarring. This is a medical procedure: it is always preceded by a consultation with one of our physicians, and downtime should be planned.',
     60, '1 to 3 sessions, 6 to 8 weeks apart', '5 to 7 days of redness and flaking', 450.00, TRUE,
     E'Can noticeably refine skin texture\nMay soften fine lines and some scars\nResults continue to develop over several months',
     E'Medical consultation required\nAntiviral medication may be prescribed if you are prone to cold sores\nNo sun exposure or tanning for 4 weeks before',
     E'Follow the written aftercare plan provided\nStrict sun avoidance and SPF 50 for 8 weeks\nNo make-up until the skin has healed',
     E'Pregnancy or breastfeeding\nIsotretinoin use in the past 12 months\nHistory of keloid scarring\nActive skin infection',
     'Fractional non-ablative laser', '1631729371254-42c2892f0e6e', 'Minimal white skincare bottles on a warm surface', TRUE, FALSE, 100),
    ('laser-light', 'IPL Photorejuvenation', 'ipl-photorejuvenation',
     'Intense pulsed light to soften the look of sun spots, redness and uneven tone.',
     'IPL delivers broad-spectrum light that is absorbed by pigment and visible blood vessels. Over a short course it can help even out the appearance of sun damage and redness on the face, neck and hands. Treated spots often darken briefly before fading.',
     40, 'Course of 3 to 5, 4 weeks apart', 'Darkening of spots for 7 to 10 days', 250.00, TRUE,
     E'Helps even out skin tone\nCan reduce the look of sun spots and redness\nTreats face, neck, décolleté and hands',
     E'No sun exposure or tanning for 4 weeks before\nStop photosensitising products as advised',
     E'Do not scratch darkened spots\nStrict SPF 50 for 4 weeks\nAvoid heat for 48 hours',
     E'Tanned or darker skin types (assessed in consultation)\nPregnancy\nPhotosensitising medication',
     'Intense pulsed light platform with filters', '1515377905703-c4788e51af15', 'Hands applying drops of facial oil', TRUE, FALSE, 98),
    ('body', 'Body Contouring', 'body-contouring',
     'Non-invasive contouring combining radiofrequency and vacuum therapy for targeted areas.',
     'A non-surgical treatment that combines radiofrequency heat with vacuum massage on areas such as the abdomen, flanks and thighs. It can improve the look of contour and skin firmness over a course of sessions when combined with a balanced lifestyle. It is not a weight-loss treatment.',
     45, 'Course of 6 to 8, weekly', 'None', 220.00, TRUE,
     E'Non-invasive, no recovery time\nCan improve the look of contour and firmness\nComfortable warming sensation',
     E'Drink plenty of water the day before\nAvoid heavy meals 2 hours before',
     E'Keep hydrated\nLight exercise helps support results',
     E'Pregnancy\nPacemaker or metal implants in the area\nActive cancer treatment',
     'Radiofrequency with vacuum therapy', '1519823551278-64ac92734fb1', 'Therapist performing a body treatment', TRUE, TRUE, 96),
    ('body', 'Cellulite Treatment', 'cellulite-treatment',
     'A targeted protocol to smooth the appearance of cellulite with mechanical massage and radiofrequency.',
     'Cellulite is common and influenced by genetics, hormones and lifestyle. Our protocol combines mechanical lymphatic massage with radiofrequency to improve circulation and smooth the appearance of dimpling. Visible improvement varies and is best maintained with periodic sessions.',
     50, 'Course of 8 to 10, once or twice weekly', 'None', 180.00, FALSE,
     E'Smoother-looking skin surface\nSupports circulation and drainage\nRelaxing, massage-like sensation',
     E'Wear comfortable clothing\nAvoid caffeine on the day',
     E'Drink water through the day\nKeep moving with light activity',
     E'Pregnancy\nVaricose veins or venous disorders in the area\nRecent surgery in the area',
     'Mechanical endermology and radiofrequency', '1544161515-4ab6ce6db874', 'Oil being applied during a body treatment', TRUE, FALSE, 94),
    ('body', 'Body Sculpting', 'body-sculpting',
     'Electromagnetic muscle stimulation to support muscle tone in the abdomen, buttocks and arms.',
     'High-intensity electromagnetic stimulation causes deep muscle contractions that you cannot achieve voluntarily. Over a course, this can support muscle tone and definition. Sessions are performed lying down and feel like an intense workout. Results vary and are best supported by regular exercise.',
     30, 'Course of 4 to 6, 2 to 3 days apart', 'Possible muscle soreness', 240.00, TRUE,
     E'Supports muscle tone and definition\nNo recovery time\nShort sessions',
     E'Remove metal jewellery and electronics\nWear comfortable clothing',
     E'Stay hydrated\nGentle stretching if muscles feel sore',
     E'Pregnancy\nPacemaker, metal implants or IUD with copper (for abdominal treatment)\nRecent surgery',
     'High-intensity focused electromagnetic stimulation', '1600334129128-685c5582fd35', 'Smooth spa stones arranged on a client’s back', TRUE, FALSE, 92),
    ('body', 'Body Skin Tightening', 'body-skin-tightening',
     'Radiofrequency treatment to support firmer-looking skin on the arms, abdomen and knees.',
     'Controlled radiofrequency heats the deeper layers of the skin to support collagen remodelling. It is used for skin laxity after weight change or with age on areas such as the arms, abdomen and above the knees. Improvement is gradual over three months.',
     45, 'Course of 4 to 6, every 2 weeks', 'None', 200.00, FALSE,
     E'Firmer-looking skin over time\nGradual, natural-looking change\nComfortable warmth',
     E'Remove body lotion on the day\nHydrate well the day before',
     E'Avoid hot baths for 24 hours\nMoisturise daily',
     E'Pregnancy\nPacemaker or metal implants in the area\nBroken skin in the area',
     'Monopolar radiofrequency', '1600334089648-b0d9d3028eb2', 'Warm stones placed along a client’s spine', TRUE, FALSE, 90),
    ('body', 'Lymphatic Drainage Massage', 'lymphatic-drainage',
     'A gentle, rhythmic manual technique that supports the lymphatic system and eases a feeling of heaviness.',
     'Performed by hand with light, rhythmic movements, lymphatic drainage supports the natural circulation of lymph. Clients often book it to relieve a feeling of heaviness or puffiness, or alongside body treatments. It is not a substitute for medical treatment of lymphoedema.',
     60, 'Single session or course of 5', 'None', 110.00, FALSE,
     E'Eases a feeling of heaviness in the legs\nCan reduce the look of puffiness\nDeeply relaxing',
     E'Avoid a large meal before\nWear loose clothing',
     E'Drink water\nRest if you can for the evening',
     E'Acute infection or fever\nHeart failure or thrombosis\nActive cancer treatment without medical approval',
     'Manual lymphatic drainage (Vodder method)', '1556760544-74068565f05c', 'Amber oil bottles beside a therapist’s hands', TRUE, FALSE, 88),
    ('anti-aging', 'Radiofrequency Skin Tightening', 'radiofrequency-skin-tightening',
     'A comfortable, non-invasive facial treatment that supports firmness along the jawline and cheeks.',
     'Radiofrequency energy gently heats the deeper layers of facial skin to support collagen production. It is suited to early laxity along the jawline, cheeks and neck. There is no downtime, and improvement develops gradually over the weeks following a course.',
     45, 'Course of 4 to 6, every 2 weeks', 'None', 260.00, FALSE,
     E'Supports firmer-looking skin\nNo downtime\nGradual, natural-looking change',
     E'Arrive without make-up if possible\nTell us about any facial implants or fillers',
     E'Apply SPF daily\nAvoid saunas for 24 hours',
     E'Pregnancy\nPacemaker or metal implants in the face\nActive skin conditions in the area',
     'Multipolar radiofrequency', '1600428877878-1a0fd85beda8', 'Facial roller, gua sha stone and serum', TRUE, TRUE, 86),
    ('anti-aging', 'Anti-Aging Facial Program', 'anti-aging-facial-program',
     'A three-month program combining in-clinic treatments with a prescribed home routine.',
     'Your specialist assesses your skin and builds a progressive plan that can combine peels, radiofrequency and LED, adjusted at each visit. A home routine with retinoids and antioxidants supports the work done in clinic. The program includes progress photographs so we can review changes together.',
     60, '6 visits over 3 months', 'Depends on the treatments chosen', 890.00, TRUE,
     E'A plan built around your priorities\nFollowed by the same specialist\nCombines in-clinic and home care',
     E'Initial consultation with skin analysis\nBring a list of the products you use at home',
     E'Follow the written home routine\nDaily broad-spectrum SPF',
     E'Contraindications depend on the treatments selected and are reviewed at consultation',
     'Combination protocol: peels, radiofrequency, LED', '1617897903246-719242758050', 'Serum bottle beside eucalyptus on wood', TRUE, FALSE, 84),
    ('anti-aging', 'Neck & Décolleté Renewal', 'neck-decollete-renewal',
     'Targeted care for the delicate skin of the neck and décolleté: texture, tone and fine lines.',
     'The neck and décolleté are often exposed to the sun and overlooked in skincare. This treatment combines a gentle peel, radiofrequency and a nourishing mask to improve the look of texture and tone. It can be booked alone or as part of a facial program.',
     45, 'Course of 3 to 4, every 3 weeks', 'Mild redness for a few hours', 210.00, FALSE,
     E'Smoother-looking skin texture\nHelps even out tone\nComfortable and relaxing',
     E'Avoid sun and self-tan for a week before\nStop retinoids on the area 3 days before',
     E'SPF on the neck and chest daily\nAvoid perfume on the area for 24 hours',
     E'Pregnancy\nBroken or sunburnt skin in the area',
     'Gentle peel, radiofrequency, nourishing mask', '1601049541289-9b1b7bbbfe19', 'Fingertip taking cream from a jar', TRUE, FALSE, 82),
    ('skin-programs', 'Personalized Skin Program', 'personalized-skin-program',
     'A fully tailored plan after an in-depth skin analysis, reviewed with you at every visit.',
     'Your program starts with a detailed consultation and skin analysis. Together we set realistic goals and a timeline, then combine treatments and a home routine in the order that suits your skin. Each visit is a review: we adjust what is not working and tell you honestly what to expect.',
     60, '4 to 8 visits over 2 to 4 months', 'Depends on the treatments chosen', 650.00, TRUE,
     E'One plan, one specialist\nRealistic goals agreed together\nAdjusted at every visit',
     E'Initial consultation with skin analysis\nComplete the health questionnaire before your first visit',
     E'Follow the personalised home routine\nDaily SPF',
     E'Reviewed individually at consultation',
     'Skin analysis imaging, combination protocols', '1590439471364-192aa70c0b53', 'Spa flat lay with towel, brush and soap', TRUE, TRUE, 80),
    ('skin-programs', 'Acne-Prone Skin Program', 'acne-prone-skin-program',
     'A structured program for congested, blemish-prone skin, in coordination with your doctor when needed.',
     'Designed for adults with persistent congestion or breakouts. We combine clarifying facials, gentle peels and blue LED with a simplified home routine. For moderate to severe acne we recommend, and can coordinate with, a medical consultation, as prescription treatment may be more appropriate.',
     50, '6 visits over 12 weeks', 'Minimal', 520.00, TRUE,
     E'A clear, simple routine\nRegular professional extraction\nSupport for the look of post-blemish marks',
     E'Bring your current products to the first visit\nTell us about any prescribed treatments',
     E'Follow the home routine consistently\nAvoid touching or squeezing blemishes',
     E'Isotretinoin use (some treatments must wait)\nPregnancy (some actives are excluded)',
     'Clarifying facials, salicylic peels, blue LED', '1531299204812-e6d44d9a185c', 'Client relaxing with cucumber slices during a facial', TRUE, FALSE, 78),
    ('skin-programs', 'Pigmentation Program', 'pigmentation-program',
     'A progressive approach to uneven tone and dark spots, built around strict sun protection.',
     'Pigmentation has many causes and is easily triggered again by sun and heat. This program combines suitable peels or light treatments with targeted home care and a strict sun protection routine. Improvement is progressive; we will be clear with you about what is realistic for your skin type.',
     50, '5 to 6 visits over 4 months', 'Mild flaking possible', 690.00, TRUE,
     E'Helps even out the appearance of skin tone\nCan soften the look of dark spots\nA routine to help prevent recurrence',
     E'Consultation required to identify the type of pigmentation\nNo sun exposure or tanning for 4 weeks before',
     E'Strict SPF 50 every day, reapplied\nAvoid heat and saunas during the program',
     E'Pregnancy\nActive sun exposure planned during the program',
     'Selected peels or IPL with targeted topicals', '1612817288484-6f916006741a', 'Skincare products arranged with smooth pebbles', TRUE, FALSE, 76),
    ('skin-programs', 'Bridal Skin Preparation', 'bridal-skin-preparation',
     'A calm, timed plan in the months before your wedding, finishing with a radiance facial in the final week.',
     'Ideally started four to six months before the date. We plan treatments so that anything with downtime happens early, and finish with gentle radiance treatments in the final weeks. Trial treatments are never scheduled close to the day.',
     60, '5 visits over 4 to 6 months', 'Planned around your date', 780.00, TRUE,
     E'A timeline built backwards from your date\nNo surprises close to the day\nIncludes a final radiance facial',
     E'Book a consultation at least 4 months before the date if possible',
     E'Follow the home routine\nAvoid trying new products in the final month',
     E'Reviewed individually at consultation',
     'Combination of facials, light peels and LED', '1509967419530-da38b4704bc6', 'Portrait of a woman with natural, luminous skin', TRUE, FALSE, 74)
) AS v(category_slug, name, slug, short_description, description, duration, sessions, downtime, price, price_from,
       benefits, preparation, aftercare, contraindications, technology, photo, alt, available, featured, age)
JOIN treatment_categories c ON c.slug = v.category_slug;

INSERT INTO treatment_images (treatment_id, image_url, alt_text, position)
SELECT t.id, pg_temp.u(v.photo, 1400), v.alt, v.position
FROM (VALUES
    ('signature-hydrafacial', '1570172619644-dfd03ed5d881', 'Mask applied with a soft brush', 0),
    ('signature-hydrafacial', '1576426863848-c21f53c60b19', 'Hydrating serum on marble', 1),
    ('facial-rejuvenation', '1600428877878-1a0fd85beda8', 'Facial roller and serum', 0),
    ('facial-rejuvenation', '1617897903246-719242758050', 'Antioxidant serum', 1),
    ('deep-skin-cleansing', '1531299204812-e6d44d9a185c', 'Calming eye pads during a facial', 0),
    ('deep-skin-cleansing', '1540555700478-4be289fbecef', 'Cleanser and towel', 1),
    ('skin-hydration-ritual', '1601049541289-9b1b7bbbfe19', 'Hydrating cream', 0),
    ('skin-hydration-ritual', '1597931752949-98c74b5b159f', 'Moisturiser pump bottle', 1),
    ('chemical-peels', '1515377905703-c4788e51af15', 'Peel solution drops', 0),
    ('chemical-peels', '1631729371254-42c2892f0e6e', 'Post-peel care products', 1),
    ('microneedling', '1620916297397-a4a5402a3c6c', 'Recovery serum', 0),
    ('microneedling', '1576426863848-c21f53c60b19', 'Serum applied after treatment', 1),
    ('led-light-therapy', '1612817288484-6f916006741a', 'Calming skincare', 0),
    ('dermaplaning', '1600428877878-1a0fd85beda8', 'Facial tools', 0),
    ('laser-hair-removal', '1620916566398-39f1143ab7be', 'Soothing gel', 0),
    ('laser-skin-resurfacing', '1552693673-1bf958298935', 'Practitioner treating the skin', 0),
    ('ipl-photorejuvenation', '1576426863848-c21f53c60b19', 'Protective serum', 0),
    ('body-contouring', '1544161515-4ab6ce6db874', 'Body treatment oil', 0),
    ('cellulite-treatment', '1556760544-74068565f05c', 'Body oils', 0),
    ('body-sculpting', '1600334089648-b0d9d3028eb2', 'Warm stones', 0),
    ('body-skin-tightening', '1590439471364-192aa70c0b53', 'Spa details', 0),
    ('lymphatic-drainage', '1519823551278-64ac92734fb1', 'Manual drainage technique', 0),
    ('radiofrequency-skin-tightening', '1512290923902-8a9f81dc236c', 'Facial massage', 0),
    ('anti-aging-facial-program', '1599305090598-fe179d501227', 'Rich cream on stone', 0),
    ('neck-decollete-renewal', '1509967419530-da38b4704bc6', 'Natural skin on the neck and shoulders', 0),
    ('personalized-skin-program', '1612817288484-6f916006741a', 'Products for a personalised routine', 0),
    ('personalized-skin-program', '1617897903246-719242758050', 'Serum', 1),
    ('acne-prone-skin-program', '1616394584738-fc6e612e71b9', 'Clarifying facial', 0),
    ('pigmentation-program', '1576426863848-c21f53c60b19', 'Brightening serum', 0),
    ('bridal-skin-preparation', '1599305090598-fe179d501227', 'Radiance cream', 0)
) AS v(slug, photo, alt, position)
JOIN treatments t ON t.slug = v.slug;

INSERT INTO treatment_faqs (treatment_id, question, answer, position)
SELECT t.id, v.question, v.answer, v.position
FROM (VALUES
    ('signature-hydrafacial', 'Is it suitable for sensitive skin?', 'Usually, yes. Serums and suction are adjusted to your skin, and your therapist checks how it responds throughout. If your skin is reactive on the day, tell us before we start.', 0),
    ('signature-hydrafacial', 'How soon will I see a difference?', 'Many clients notice that their skin looks fresher straight after the treatment. Longer-term changes depend on your skin and routine, and vary from person to person.', 1),
    ('signature-hydrafacial', 'Can I wear make-up afterwards?', 'We recommend leaving the skin bare for the rest of the day, but light mineral make-up is fine if needed.', 2),
    ('chemical-peels', 'Will my skin peel visibly?', 'It depends on the peel. Light peels rarely cause visible peeling; medium-strength peels can cause flaking for 3 to 7 days. We will tell you what to expect before booking.', 0),
    ('chemical-peels', 'How many peels will I need?', 'Most concerns respond best to a course of 3 to 6 peels. Your specialist will suggest a plan after assessing your skin.', 1),
    ('chemical-peels', 'Can I have a peel in summer?', 'Lighter peels can be performed year-round with strict sun protection. Stronger peels are best planned in autumn and winter.', 2),
    ('microneedling', 'Does microneedling hurt?', 'A topical anaesthetic is applied 20 to 30 minutes beforehand, so most clients describe a light scratching sensation rather than pain.', 0),
    ('microneedling', 'When will I see results?', 'Skin renewal takes time. Changes in texture usually develop over the weeks after each session and continue across the course. Results vary between individuals.', 1),
    ('laser-hair-removal', 'Why do I need several sessions?', 'Hair grows in cycles and the laser only affects follicles in the active growth phase, so several sessions are needed to reach each follicle at the right time.', 0),
    ('laser-hair-removal', 'Is it suitable for all skin tones?', 'Our diode laser can treat a wide range of skin tones with appropriate settings. A patch test and consultation confirm what is safe for you.', 1),
    ('laser-skin-resurfacing', 'Who performs the treatment?', 'Laser resurfacing is performed by one of our physicians after a medical consultation.', 0),
    ('laser-skin-resurfacing', 'How much time off should I plan?', 'Plan for 5 to 7 days of visible redness and flaking. Most clients prefer to schedule it before a quiet week.', 1),
    ('body-contouring', 'Will I lose weight?', 'No. Body contouring is not a weight-loss treatment. It can improve the look of contour and skin firmness in targeted areas when combined with a balanced lifestyle.', 0),
    ('body-contouring', 'What does it feel like?', 'A deep warmth combined with a massage-like suction. Most clients find it comfortable.', 1),
    ('cellulite-treatment', 'Can cellulite be removed completely?', 'Cellulite can be improved but rarely removed completely. We will set realistic expectations together at your consultation.', 0),
    ('radiofrequency-skin-tightening', 'Is there any downtime?', 'No. You may look slightly flushed for an hour, then you can return to your normal activities.', 0),
    ('radiofrequency-skin-tightening', 'When will I see a change?', 'Collagen remodelling is gradual: changes typically develop over two to three months after a course. Individual results vary.', 1),
    ('personalized-skin-program', 'What happens at the first consultation?', 'We discuss your concerns, history and routine, analyse your skin and agree on goals and a timeline. There is no obligation to start the program.', 0),
    ('personalized-skin-program', 'Can the plan change along the way?', 'Yes. Each visit is a review, and we adjust treatments based on how your skin responds.', 1),
    ('pigmentation-program', 'Why is sun protection so important?', 'Pigmentation is easily stimulated by UV and visible light. Without strict daily protection, treatments are far less effective and spots often return.', 0),
    ('bridal-skin-preparation', 'When should I start?', 'Ideally four to six months before the date, so that any treatment with downtime happens well ahead of the day.', 0),
    ('led-light-therapy', 'Is LED safe for the eyes?', 'You wear protective goggles throughout. LED treatment does not use UV light.', 0),
    ('acne-prone-skin-program', 'Do I need to see a doctor?', 'For persistent, painful or scarring acne we recommend a medical consultation, as prescription treatment may be more appropriate. We can coordinate with your doctor.', 0)
) AS v(slug, question, answer, position)
JOIN treatments t ON t.slug = v.slug;

INSERT INTO specialists (name, slug, role, bio, photo, experience, specialties, instagram_url, linkedin_url, display_order) VALUES
    ('Dr. Hélène Marchetti', 'helene-marchetti', 'Medical Director, Aesthetic Physician',
     'Dr. Marchetti trained in general medicine before specialising in aesthetic medicine. She leads every medical consultation at Éloria and believes the most important part of her work is the conversation before any treatment: understanding what a client hopes for, and being honest about what is realistic.',
     pg_temp.u('1559839734-2b71ea197ec2', 900, 1125, TRUE), '16 years in aesthetic medicine',
     E'Medical consultations\nLaser resurfacing\nSkin quality programs', NULL, 'https://www.linkedin.com/', 1),
    ('Dr. Karim Benali', 'karim-benali', 'Aesthetic Physician, Laser & Light',
     'Dr. Benali focuses on laser and light-based treatments. He is known for careful, conservative settings and for explaining each step before he begins. He oversees our laser safety protocols and trains the team on new devices.',
     pg_temp.u('1612531385446-f7e6d131e1d0', 900, 1125, TRUE), '11 years in laser medicine',
     E'Laser hair removal\nIPL photorejuvenation\nPigmentation', NULL, 'https://www.linkedin.com/', 2),
    ('Camille Rousseau', 'camille-rousseau', 'Lead Aesthetic Nurse',
     'Camille coordinates our clinical treatments and follows clients through their programs. With a background in dermatology nursing, she brings a precise, reassuring approach to peels, microneedling and post-treatment care.',
     pg_temp.u('1594824476967-48c8b964273f', 900, 1125, TRUE), '9 years in dermatology nursing',
     E'Chemical peels\nMicroneedling\nAftercare follow-up', 'https://www.instagram.com/', NULL, 3),
    ('Inès Lefèvre', 'ines-lefevre', 'Senior Skin Therapist',
     'Inès designs our facial protocols and leads the Signature Hydrafacial. She has a gift for reading skin on the day and adapting a treatment in real time, and a calm presence clients often mention.',
     pg_temp.u('1580489944761-15a19d654956', 900, 1125, TRUE), '12 years as a skin therapist',
     E'Signature facials\nSensitive skin\nAcne-prone skin', 'https://www.instagram.com/', NULL, 4),
    ('Sophie Laurent', 'sophie-laurent', 'Body Treatment Specialist',
     'Sophie specialises in body treatments and manual lymphatic drainage. She sets clear, realistic goals with every client and combines devices with hands-on techniques for comfortable, effective sessions.',
     pg_temp.u('1508214751196-bcfd4ca60f91', 900, 1125, TRUE), '10 years in body therapies',
     E'Body contouring\nLymphatic drainage\nCellulite treatments', NULL, NULL, 5),
    ('Margaux Dubois', 'margaux-dubois', 'Client Experience Manager',
     'Margaux is often the first person you speak to. She organises consultations, answers questions about programs and pricing, and makes sure every visit runs calmly and on time.',
     pg_temp.u('1573496359142-b8d87734a5a2', 900, 1125, TRUE), '8 years in luxury hospitality',
     E'Consultation planning\nPrograms and pricing\nClient care', NULL, 'https://www.linkedin.com/', 6);

-- Demonstration before/after images live in the frontend at /demo/results (tight crops of placeholder photography,
-- not patient results). Every description says so; replace them with consented patient photographs.
INSERT INTO results (treatment_id, before_image_url, after_image_url, title, description, duration_label, featured, display_order)
SELECT t.id, '/demo/results/' || v.file || '-before.jpg', '/demo/results/' || v.file || '-after.jpg', v.title,
       v.description || ' Demonstration images for this preview site.', v.duration, v.featured, v.position
FROM (VALUES
    ('signature-hydrafacial', 'hydrafacial-radiance', 'Radiance after a Hydrafacial course', 'Dull, dehydrated skin treated with monthly Signature Hydrafacials. The skin appears more luminous and even.', '3 sessions over 3 months', TRUE, 1),
    ('chemical-peels', 'clarifying-peel', 'Smoother texture after peels', 'A course of light glycolic peels for uneven texture, combined with a simplified home routine.', '4 peels over 10 weeks', TRUE, 2),
    ('microneedling', 'microneedling-texture', 'Refined texture with microneedling', 'Microneedling for enlarged-looking pores and mild textural irregularities.', '3 sessions over 4 months', TRUE, 3),
    ('skin-hydration-ritual', 'hydration-glow', 'Comfort for dehydrated skin', 'Hydration Rituals for skin that felt tight after winter, with a barrier-repair routine at home.', '4 sessions over 8 weeks', FALSE, 4),
    ('pigmentation-program', 'even-tone-program', 'A more even tone', 'Pigmentation Program combining gentle peels with strict daily sun protection.', '5 visits over 4 months', TRUE, 5),
    ('body-contouring', 'body-contour', 'Body contouring course', 'Radiofrequency and vacuum therapy on the lower back and flanks, alongside regular activity.', '8 sessions over 8 weeks', FALSE, 6),
    ('radiofrequency-skin-tightening', 'jawline-rf', 'Jawline firmness with radiofrequency', 'Radiofrequency for early laxity along the jawline. Changes developed gradually after the course.', '5 sessions over 10 weeks', TRUE, 7),
    ('acne-prone-skin-program', 'clear-skin-program', 'Calmer, clearer skin', 'Acne-Prone Skin Program with clarifying facials, salicylic peels and blue LED.', '6 visits over 12 weeks', FALSE, 8)
) AS v(slug, file, title, description, duration, featured, position)
JOIN treatments t ON t.slug = v.slug;

INSERT INTO gallery_images (title, description, image_url, category, display_order, featured) VALUES
    -- Editorial
    ('The Signature Hydrafacial', 'Cleanse, extract, hydrate: our most requested facial.', pg_temp.u('1616394584738-fc6e612e71b9', 1200, 1500), 'TREATMENTS', 1, TRUE),
    ('Hands-on precision', 'Manual techniques remain at the heart of our facials.', pg_temp.u('1512290923902-8a9f81dc236c', 1600, 1067), 'TREATMENTS', 2, FALSE),
    ('A considered mask', 'Every mask is chosen for the skin in front of us.', pg_temp.u('1570172619644-dfd03ed5d881', 1200, 1600), 'TREATMENTS', 3, FALSE),
    ('Clinical care', 'Advanced treatments are performed with medical-grade protocols.', pg_temp.u('1552693673-1bf958298935', 1600, 1200), 'TREATMENTS', 4, TRUE),
    ('Body rituals', 'Warm oils and slow, attentive movements.', pg_temp.u('1544161515-4ab6ce6db874', 1600, 1067), 'TREATMENTS', 5, FALSE),
    ('Drainage', 'Manual lymphatic drainage, performed by hand.', pg_temp.u('1519823551278-64ac92734fb1', 1000, 1500), 'TREATMENTS', 6, FALSE),
    ('Natural light', 'Skin as it is, without filters.', pg_temp.u('1509967419530-da38b4704bc6', 1600, 1100), 'SKIN', 7, TRUE),
    ('Quiet confidence', 'Healthy skin starts with an honest conversation.', pg_temp.u('1531123897727-8f129e1688ce', 1100, 1500), 'SKIN', 8, FALSE),
    ('Freckles welcome', 'We treat concerns, not character.', pg_temp.u('1438761681033-6461ffad8d80', 1200, 1500), 'SKIN', 9, FALSE),
    ('Golden hour', 'Radiance, gently supported.', pg_temp.u('1544005313-94ddf0286df2', 1100, 1500), 'SKIN', 10, FALSE),
    ('Texture study', 'Cream textures chosen for comfort.', pg_temp.u('1599305090598-fe179d501227', 1200, 1200), 'BEAUTY', 11, TRUE),
    ('The serum', 'Active formulations, measured drop by drop.', pg_temp.u('1576426863848-c21f53c60b19', 1200, 1600), 'BEAUTY', 12, FALSE),
    ('Daily ritual', 'A home routine that continues our work.', pg_temp.u('1601049541289-9b1b7bbbfe19', 1600, 1100), 'BEAUTY', 13, FALSE),
    ('Pure formulas', 'Simple, effective, well tolerated.', pg_temp.u('1631729371254-42c2892f0e6e', 1200, 1500), 'BEAUTY', 14, FALSE),
    ('Pigment', 'Colour, applied with restraint.', pg_temp.u('1503236823255-94609f598e71', 1200, 1200), 'BEAUTY', 15, FALSE),
    ('Slow mornings', 'A moment of stillness before treatment.', pg_temp.u('1507652313519-d4e9174996dd', 1600, 1067), 'ATMOSPHERE', 16, TRUE),
    ('Botanicals', 'Eucalyptus, warm wood and amber glass.', pg_temp.u('1617897903246-719242758050', 1200, 1500), 'ATMOSPHERE', 17, FALSE),
    ('Stillness', 'Linen, light and nothing extra.', pg_temp.u('1590439471364-192aa70c0b53', 1200, 1200), 'ATMOSPHERE', 18, FALSE),
    ('Warm stones', 'Heat to release tension before body treatments.', pg_temp.u('1600334089648-b0d9d3028eb2', 1600, 1067), 'ATMOSPHERE', 19, FALSE),
    ('The courtyard', 'Light and greenery to slow the pace.', pg_temp.u('1560750588-73207b1ef5b8', 1200, 1500), 'ATMOSPHERE', 20, FALSE),
    -- The Center
    ('Reception', 'A calm welcome, never a queue.', pg_temp.u('1618221195710-dd6b41faaea6', 1600, 1000), 'RECEPTION', 21, TRUE),
    ('Arrival', 'Natural materials and soft daylight.', pg_temp.u('1618219908412-a29a1bb7b86e', 1200, 1500), 'RECEPTION', 22, FALSE),
    ('The lounge', 'Where consultations begin.', pg_temp.u('1556228453-efd6c1ff04f6', 1600, 1100), 'WAITING_AREA', 23, TRUE),
    ('Quiet corner', 'Herbal infusions while you wait.', pg_temp.u('1616486338812-3dadae4b4ace', 1200, 1500), 'WAITING_AREA', 24, FALSE),
    ('Treatment suite', 'Private rooms with adjustable light.', pg_temp.u('1631049307264-da0ec9d70304', 1600, 1067), 'TREATMENT_ROOMS', 25, TRUE),
    ('Body suite', 'Heated beds and warm linens.', pg_temp.u('1600334129128-685c5582fd35', 1200, 1500), 'TREATMENT_ROOMS', 26, FALSE),
    ('Clinical equipment', 'Medical-grade devices, maintained and calibrated.', pg_temp.u('1515377905703-c4788e51af15', 1600, 1100), 'EQUIPMENT', 27, FALSE),
    ('Tools of precision', 'Single-use, sterile instruments.', pg_temp.u('1600428877878-1a0fd85beda8', 1200, 1200), 'EQUIPMENT', 28, FALSE),
    ('Living room', 'Soft seating and warm textures throughout.', pg_temp.u('1615529182904-14819c35db37', 1600, 1067), 'INTERIOR', 29, FALSE),
    ('Light and air', 'High ceilings and tall windows.', pg_temp.u('1600210492486-724fe5c67fb0', 1200, 1500), 'INTERIOR', 30, FALSE),
    ('Evening light', 'Late appointments in a softer mood.', pg_temp.u('1564078516393-cf04bd966897', 1600, 1067), 'INTERIOR', 31, FALSE),
    ('Washroom', 'Considered down to the details.', pg_temp.u('1629079447777-1e605162dc8d', 1200, 1500), 'INTERIOR', 32, FALSE),
    ('Our building', 'A discreet facade in the 8th arrondissement.', pg_temp.u('1600585154340-be6161a56a0c', 1600, 1067), 'EXTERIOR', 33, FALSE),
    ('The entrance', 'Glass, wood and a quiet street.', pg_temp.u('1600566753190-17f0baa2a6c3', 1200, 1500), 'EXTERIOR', 34, FALSE),
    ('Details', 'Amber glass and natural textures.', pg_temp.u('1556760544-74068565f05c', 1200, 1200), 'DETAILS', 35, FALSE),
    ('Fresh linen', 'Changed after every client.', pg_temp.u('1540555700478-4be289fbecef', 1200, 1500), 'DETAILS', 36, FALSE),
    ('Our medical director', 'Dr. Hélène Marchetti.', pg_temp.u('1559839734-2b71ea197ec2', 1200, 1500, TRUE), 'TEAM', 37, FALSE),
    ('Our nursing team', 'Camille Rousseau, lead aesthetic nurse.', pg_temp.u('1594824476967-48c8b964273f', 1200, 1500, TRUE), 'TEAM', 38, FALSE);

INSERT INTO testimonials (author_name, author_detail, quote, treatment_name, display_order, published) VALUES
    ('Claire M.', 'Client since 2024', 'What I valued most was the first consultation. Nobody tried to sell me anything; they explained what was realistic for my skin and built a plan around it.', 'Personalized Skin Program', 1, TRUE),
    ('Anaïs D.', 'Paris 16e', 'The Hydrafacial has become my monthly hour of calm. My skin looks rested and the team remembers exactly how it reacted last time.', 'Signature Hydrafacial', 2, TRUE),
    ('Julien R.', 'Client since 2025', 'I was nervous about laser treatment. Dr. Benali walked me through every step and the settings were adjusted after the patch test. Very reassuring.', 'Laser Hair Removal', 3, TRUE),
    ('Sofia L.', 'Neuilly-sur-Seine', 'Camille followed my peel course from start to finish. Clear instructions, quick answers when I had questions, and no pressure at any point.', 'Chemical Peels', 4, TRUE),
    ('Nathalie B.', 'Client since 2023', 'A beautiful place, but what keeps me coming back is the honesty. When a treatment wasn’t right for me, they told me so.', 'Anti-Aging Facial Program', 5, TRUE),
    ('Émilie T.', 'Paris 8e', 'I started my bridal program five months before the wedding. Everything was timed so that the last weeks were only gentle, glowing treatments.', 'Bridal Skin Preparation', 6, TRUE),
    ('Hugo P.', 'Client since 2025', 'Efficient, discreet and precise. The lymphatic drainage sessions with Sophie are the best I’ve had.', 'Lymphatic Drainage Massage', 7, TRUE);

-- A few requests and messages so the admin dashboard is not empty on first run.
INSERT INTO appointments (name, email, phone, treatment_id, treatment_name, preferred_date, preferred_time, message, status, admin_notes, created_at, updated_at)
SELECT v.name, v.email, v.phone, t.id, t.name, current_date + v.in_days, v.slot, v.message, v.status, v.notes,
       now() - (v.age_hours || ' hours')::interval, now() - (v.age_hours || ' hours')::interval
FROM (VALUES
    ('Léa Martin', 'lea.martin@example.com', '+33 6 12 34 56 78', 'signature-hydrafacial', 3, '10:30', 'First visit. I have combination skin and a wedding to attend next month.', 'PENDING', NULL, 2),
    ('Thomas Girard', 'thomas.girard@example.com', '+33 6 23 45 67 89', 'laser-hair-removal', 5, '18:00', 'Interested in back and shoulders. Can I do the patch test the same week?', 'PENDING', NULL, 7),
    ('Amélie Roux', 'amelie.roux@example.com', '+33 7 45 12 98 30', 'personalized-skin-program', 6, '14:00', 'I would like a consultation about pigmentation on my cheeks.', 'PENDING', NULL, 20),
    ('Chloé Bernard', 'chloe.bernard@example.com', '+33 6 87 65 43 21', 'chemical-peels', 2, '11:00', NULL, 'CONFIRMED', 'Confirmed by phone. Consultation first, peel the same day if suitable.', 30),
    ('Nadia Haddad', 'nadia.haddad@example.com', '+33 6 55 44 33 22', 'microneedling', 9, '16:30', 'I had acne scarring treated elsewhere before; happy to share details.', 'CONFIRMED', 'Asked her to bring previous treatment records.', 52),
    ('Pauline Lemoine', 'pauline.lemoine@example.com', '+33 6 11 22 33 44', 'body-contouring', 4, '09:30', NULL, 'CONFIRMED', NULL, 70),
    ('Marc Fontaine', 'marc.fontaine@example.com', '+33 6 98 76 54 32', 'lymphatic-drainage', -3, '19:00', NULL, 'COMPLETED', 'Booked a course of 5.', 140),
    ('Isabelle Moreau', 'isabelle.moreau@example.com', '+33 6 21 43 65 87', 'facial-rejuvenation', -6, '12:00', NULL, 'COMPLETED', NULL, 210),
    ('Sarah Cohen', 'sarah.cohen@example.com', '+33 7 81 92 03 14', 'skin-hydration-ritual', -9, '15:00', NULL, 'COMPLETED', NULL, 300),
    ('Julie Petit', 'julie.petit@example.com', '+33 6 32 54 76 98', 'ipl-photorejuvenation', 1, '10:00', 'Sun spots on my hands and face.', 'CANCELLED', 'Recently tanned: postponed to November.', 96),
    ('Camille Duval', 'camille.duval@example.com', '+33 6 74 85 96 07', 'radiofrequency-skin-tightening', 12, '13:30', NULL, 'PENDING', NULL, 1),
    ('Manon Leroy', 'manon.leroy@example.com', '+33 6 41 52 63 74', 'bridal-skin-preparation', 14, '17:00', 'Wedding in early March.', 'CONFIRMED', 'Program plan sent by email.', 400),
    ('Antoine Mercier', 'antoine.mercier@example.com', '+33 6 85 96 07 18', 'acne-prone-skin-program', 8, '18:30', NULL, 'PENDING', NULL, 12),
    ('Eva Garnier', 'eva.garnier@example.com', '+33 7 19 28 37 46', 'neck-decollete-renewal', -14, '11:30', NULL, 'COMPLETED', NULL, 520)
) AS v(name, email, phone, slug, in_days, slot, message, status, notes, age_hours)
JOIN treatments t ON t.slug = v.slug;

INSERT INTO contact_messages (name, email, phone, message, status, created_at, updated_at) VALUES
    ('Hélène Vasseur', 'helene.vasseur@example.com', '+33 6 14 25 36 47', 'Hello, do you offer gift vouchers for a facial? I would like to offer one for a birthday in two weeks.', 'NEW', now() - interval '3 hours', now() - interval '3 hours'),
    ('Romain Blanc', 'romain.blanc@example.com', NULL, 'Is laser hair removal possible on darker skin types with your device? I would like to know before booking a consultation.', 'NEW', now() - interval '20 hours', now() - interval '20 hours'),
    ('Laura Simon', 'laura.simon@example.com', '+33 7 36 47 58 69', 'Could you tell me whether the Personalized Skin Program can be paid in several instalments?', 'NEW', now() - interval '2 days', now() - interval '2 days'),
    ('Victor Chevalier', 'victor.chevalier@example.com', NULL, 'Thank you for the lovely welcome last week. Do you have parking nearby?', 'READ', now() - interval '5 days', now() - interval '4 days'),
    ('Océane Faure', 'oceane.faure@example.com', '+33 6 47 58 69 70', 'I am pregnant: which facials can I safely have during the second trimester?', 'READ', now() - interval '8 days', now() - interval '7 days'),
    ('Benoît Lambert', 'benoit.lambert@example.com', NULL, 'Do you work with corporate partnerships for employee wellbeing days?', 'ARCHIVED', now() - interval '20 days', now() - interval '18 days');
